# List of national identifiers registers issued by European Central Bank, used to manually verify identifiers
ECB_NATIONAL_IDENTIFIERS_REGISTERS = {
    'AT_FB_CD': ('https://www.firmenabc.at/', 'https://firmenbuch.at'),
    'AT_GEM_CD': 'http://www.statistik.at/web_de/klassifikationen/regionale_gliederungen/gemeinden/index.html',
    'AT_IDENT_CD': 'https://www.usp.gv.at/Portal.Node/usp/public/content/laufender_betrieb/firmenbuch/firmenbuchabfrage/Seite.760006.html',  # noqa: E501
    'AT_LAE_CD': 'http://www.iso.org/iso/home/store/catalogue_ics/catalogue_detail_ics.htm?csnumber=63546',
    'AT_ZVR_CD': 'http://zvr.bmi.gv.at/Start',
    'BE_OND_CD': 'http://kbopub.economie.fgov.be/kbopub/zoeknummerform.html?lang=en',
    'BG_BULSTAT_CD': 'http://reports.bulstat.bg:8081/bulstat-ireports/report.jsf?x_rpt=rpt1',
    'BG_UIC_CD': 'https://public.brra.bg/CheckUps/Verifications/VerificationPersonOrg.ra',
    'BG_VAT_CD': 'http://nra.bg/vatbulletin/',
    'BR_CNPJ_CD': (
        'http://www.receita.fazenda.gov.br/PessoaJuridica/CNPJ/cnpjreva/Cnpjreva_Solicitacao.asp',
        'https://www.infoplex.com.br/'),
    'CA_BN_CD': ('http://www.cra-arc.gc.ca/bn/', 'https://beta.canadasbusinessregistries.ca/search'),
    'CH_UID_CD': ('https://www.uid.admin.ch', 'https://www.zefix.ch/en/search/entity/welcome'),
    'CN_CC_CD': 'http://bj.gsxt.gov.cn/',
    'CY_CBCID_CD': 'https://www.centralbank.cy/images/media/xls/CY_CBCID_CD.xlsx',
    'CY_DRCOR_CD': 'https://efiling.drcor.mcit.gov.cy/DrcorPublic/SearchForm.aspx?sc=0&cultureInfo=en-AU',
    'CY_GG_CD': 'https://www.centralbank.cy/images/media/xls/CY_GG_CD.xlsx',
    'CY_IF_CD': 'https://www.centralbank.cy/en/statistics/money-and-banking-statistics-and-financial-accounts/lists-of-financial-institutions',  # noqa: E501
    'CZ_ICO_CD': ('https://or.justice.cz/ias/ui/rejstrik', 'https://apl.czso.cz/irsw/'),
    'CZ_NID_CD': 'https://apl.cnb.cz/apljerrsdad/JERRS.WEB15.BASIC_LISTINGS?p_lang=cz',
    'DE_GNR_CD': 'https://www.handelsregister.de/rp_web/welcome.do',
    'DE_HRA_CD': 'https://www.handelsregister.de/rp_web/welcome.do',
    'DE_HRB_CD': 'https://www.handelsregister.de/rp_web/welcome.do',
    'DE_PR_CD': 'https://www.handelsregister.de/rp_web/welcome.do',
    'DE_VR_CD': 'https://www.handelsregister.de/rp_web/welcome.do',
    'DK_CVR_CD': 'http://www.cvr.dk',
    'DK_FT_CD': 'http://vut.finanstilsynet.dk/en/Tal-og-fakta/Virksomheder-under-tilsyn/VUT-database.aspx',
    'EE_RG_CD': 'https://ariregister.rik.ee/',
    'ES_NIF_CD': 'http://www.infocif.es/',
    'FI_ALV_CD': 'http://fi.vat-search.eu/',
    'FI_SIRA_CD': 'http://www.suomenpankki.fi/en/tilastot/sijoitusrahastot/Pages/sijoitusrahastolista.aspx',
    'FI_Y_CD': 'https://tietopalvelu.ytj.fi/yrityshaku.aspx?kielikoodi=3',
    'FR_CIB': 'https://www.regafi.fr/spip.php?rubrique3',
    'FR_IF_CD': 'https://www.ecb.europa.eu/stats/financial_corporations/list_of_financial_institutions/html/index.en.html',  # noqa: E501
    'FR_RNA_CD': 'https://www.data.gouv.fr/fr/datasets/repertoire-national-des-associations-rna/',
    'FR_SIREN_CD': 'https://www.sirene.fr/sirene/public/accueil',
    'GB_CRN_CD': 'https://beta.companieshouse.gov.uk',
    'GB_UTR_CD': 'https://www.gov.uk/government/organisations/hm-revenue-customs',
    'GR_IMO_CD': 'http://www.imonumbers.lrfairplay.com/',
    'HK_CR_CD': ('https://www.icris.cr.gov.hk/csci/login_i.do?loginType=iguest&OPT_01=1&OPT_02=1&OPT_03=1&OPT_04=1&OPT_05=1&OPT_06=1&OPT_07=1&OPT_08=1&OPT_09=1',  # noqa: E501
                 'http://www.hongkongcompanylist.com/'),
    'HR_MBS_CD': 'https://sudreg.pravosudje.hr/registar/',
    'HR_MB_CD': 'http://www.dzs.hr/',
    'HR_OIB_CD': 'http://oib.oib.hr/SaznajOibWeb/pravnaOsoba.html',
    'HU_CEG_CD': 'https://www.e-cegjegyzek.hu/?cegkereses',
    'IE_CRO_CD': 'https://search.cro.ie',
    'IE_GOV_CD': 'https://www.centralbank.ie/statistics/statistical-reporting-requirements/anacredit-in-ireland',
    'IN_CIN_CD': 'http://www.mca.gov.in/mcafoportal/checkCompanyName.do',
    'IT_UCITS_CD': 'https://infostat.bancaditalia.it/giava-inquiry-public/flex/Giava/GIAVAFEInquiry.html#',
    'JP_CN_CD': ('http://www.nta.go.jp/foreign_language/corporate_number/',
                 'https://www2.tse.or.jp/tseHpFront/JJK020010Action.do?Show=Show'),
    'LT_JAR_CD': 'http://www.registrucentras.lt/jar/index_en.php',
    'LU_IF_CD': 'https://supervisedentities.apps.cssf.lu/index.html?language=fr&type=OPC#Home',
    'LU_RCS_CD': 'https://lu.kompass.com',
    'LU_VAT_CD': 'https://lu.kompass.com',
    'LV_FON_CD': 'https://www.bank.lv/en/statistics/information-for-data-users/lists/investment-funds-of-the-republic-of-latvia',  # noqa: E501
    'LV_NBR_CD': 'http://www.lursoft.lv/en/data-bases-of-companies',
    'LV_VAT_CD': 'http://www.lursoft.lv/en/data-bases-of-companies',
    'MC_CIB': 'https://www.regafi.fr/spip.php?rubrique3',
    'MC_NIS_CD': 'http://www.imsee.mc/Demarches-et-Services/Repertoire-du-NIS',
    'MC_RCI_CD': 'http://www.rci.gouv.mc/rc/',
    "MT_CNUM_CD": "https://registry.mbr.mt/ROC/index.jsp#companySearch.do?action=companyDetails",
    'MX_RFC_CD': ('https://www.gob.mx/busqueda',
                  'https://www.dateas.com/es/explore/empresas-mexicanas/'),
    'NL_KVK_CD': 'http://www.kvk.nl',
    'NL_RSIN_CD': 'http://www.kvk.nl',
    'NO_NBR_CD': 'https://w2.brreg.no/enhet/sok/',
    'PL_KRS_CD': 'https://ems.ms.gov.pl/krs/wyszukiwaniepodmiotu?t:lb=t',
    'PL_NIP_CD': 'https://ems.ms.gov.pl/krs/wyszukiwaniepodmiotu?t:lb=t',
    'PL_REGON_CD': 'https://ems.ms.gov.pl/krs/wyszukiwaniepodmiotu?t:lb=t',
    'PL_VAT_CD': 'https://ems.ms.gov.pl/krs/wyszukiwaniepodmiotu?t:lb=t',
    'PT_FSA_CD': 'http://www.bportugal.pt',
    'RO_TRN_CD': 'https://www.listafirme.ro',
    'RU_INN_CD': ('https://service.nalog.ru/inn.do', 'https://www.k-agent.ru/en'),
    'SE_FIN_CD': 'http://www.fi.se/Folder-EN/Startpage/Register/Company-register/',
    'SE_ORG_CD': 'http://www.bolagsverket.se/en/info/buy/e-services/company-information',
    'SI_DAV_CD': 'http://www.ajpes.si/prs/default.asp',
    'SI_DDV_CD': 'http://www.ajpes.si/prs/default.asp',
    'SI_MAT_CD': 'http://www.ajpes.si/prs/default.asp',
    'SK_ICO_CD': 'https://rpo.statistics.sk/rpo',
    'SK_IF_CD': 'https://www.nbs.sk/en/statistics/financial-institutions/money-market-funds-and-investment-funds/list-of-investment-funds',  # noqa: E501
    'TR_VKN_CD': 'https://www.nvi.gov.tr/',
    'US_EIN_CD': ('https://www.irs.gov/businesses/small-businesses-self-employed/employer-id-numbers-eins',
                  'https://eintaxid.com/')
}

# List of national identifiers issued by European Central Bank
ECB_NATIONAL_IDENTIFIERS = {
    "AT_FB_CD": "^[0-9]{1,6}[A-Za-z][0-9]{0,3}$",
    "AT_GEM_CD": "^[0-9]{5}$",
    "AT_IDENT_CD": "^[0-9]{1,8}$",
    "AT_LAE_CD": "^[0-9]$",
    "AT_ZVR_CD": "^[0-9]{1,10}$",
    "BE_OND_CD": "^0[0-9]{9}$",
    "BG_BULSTAT_CD": "(^[0-9]{9}$)|(^[0-9]{10}$)|(^[0-9]{13}$)",
    "BG_UIC_CD": "(^[0-9]{9}$)|(^[0-9]{13}$)$",
    "BG_VAT_CD": "^BG([0-9]{9,10})$",
    "BIC": "(^[A-Z0-9]{8}$)|(^[A-Z0-9]{11}$)$",
    "BR_CNPJ_CD": "^[0-9]{2}[.][0-9]{3}[.][0-9]{3}/[0-9]{4}-[0-9]{2}$",
    "CA_BN_CD": "^[0-9]{9}$",
    "CH_ID_CD": "^CH[0-9]{11}$",
    "CH_NUMMER": "^CH-[0-9]{3}[.][0-9][.][0-9]{3}[.][0-9]{3}-[0-9]$",
    "CH_UID_CD": "^CHE-[0-9]{3}[.][0-9]{3}[.][0-9]{3}$",
    "CN_CC_CD": "^[A-Z0-9]{18}$",
    "CY_DRCOR_CD": "^[COP][0-9]{1,8}$",
    "CY_TIC_CD": "^[0-9]{8}[A-Z]$",
    "CY_IF_CD": "^CYIF[0-9]{4}$",
    "CY_PF_CD": "^PF[0-9]{1,4}$",
    "CY_GG_CD": "^S13[0-9]{8}$",
    "CY_VAT_CD": "^[013459][0-9]{7}[A-Z]$",
    "CY_CBCID_CD": "^[A-Z]{2}[0-9]{1,8}$",
    "CZ_ICO_CD": "^[0-9]{8}$",
    "CZ_NID_CD": "(^[0-9]{8}$)|(^[0-9]{10}$)",
    "DE_GNR_CD": "^G[nN]R[0-9]{1,6}[A-Z]{0,5}-[A-Z][0-9]{4}$",
    "DE_HRA_CD": "^HRA[0-9]{1,6}[A-Z]{0,5}-[A-Z][0-9]{4}$",
    "DE_HRB_CD": "^HRB[0-9]{1,6}[A-Z]{0,5}-[A-Z][0-9]{4}$",
    "DE_PR_CD": "^PR[0-9]{1,6}[A-Z]{0,5}-[A-Z][0-9]{4}$",
    "DE_VR_CD": "^VR[0-9]{1,6}[A-Z]{0,5}-[A-Z][0-9]{4}$",
    "DE_VAT_CD": "^DE[0-9]{9}$",
    "DE_TAX_CD": "^[0-9]{13}$",
    "DK_CVR_CD": "^[0-9]{8}$",
    "DK_FT_CD": "(^[0-9]+$)|(^[0-9]+-[0-9]+$)",
    "DK_SE_CD": "^[0-9]{8}$",
    "EE_FON_CD": "^[0-9]{1,4}$",
    "EE_RG_CD": "^[0-9]{8}$",
    "ES_NIF_CD": "^[A-Z0-9]{9}$",
    "FI_ALV_CD": "^FI[0-9]{8}$",
    "FI_SIRA_CD": "^[0-9]{8}#[0-9]{3}$",
    "FI_Y_CD": "^[0-9]{7}-?[0-9]$",
    "FR_CIB": "^[0-9]{5}$",
    "FR_RNA_CD": "^[A-Z][0-9]{9}$",
    "FR_SIREN_CD": "^[0-9]{9}$",
    "FR_IF_CD": "^FR[A-Z0-9]{10}$",
    "GB_VAT_CD": "^(GB([0-9]{9}|[0-9]{12})|GB(GD|HA)[0-9]{3})$",
    "GB_FSR_CD": "^[0-9]{6}$",
    "GB_CRN_CD": "^[A-Z0-9]{8}$",
    "GB_UTR_CD": "(^[0-9]{10}$)|(^[0-9]{9}K$)",
    "GR_AFM_CD": "^[0-9]{9}$",
    "GR_IMO_CD": "^[0-9]{7}$",
    "HK_BR_CD": "^[0-9]{8}-[0-9]{3}.[0-9]{2}.[0-9]{2}-[A-Z]$",
    "HK_CR_CD": "^([A-Z]{1}[0-9]{7}|[0-9]{7})$",
    "HR_MB_CD": "^[0-9]{8}$",
    "HR_MBS_CD": "^[01][0-9]{8}$",
    "HR_OIB_CD": "^[0-9]{11}$",
    "HU_CEG_CD": "^[0-9]{2}-[0-9]{2}-[0-9]{6}$",
    "HU_FB_CD": "^FB([0-9]{6}|[0-9]{3}[A-Z][0-9]{2})$",
    "HU_KOZ_CD": "^HU[0-9]{8}$",
    "HU_TOR_CD": "^[0-9]{8}$",
    "IE_CRO_CD": "^[1-9][0-9]{0,6}$",
    "IE_GOV_CD": "^(GV[0-9]{4}|LA[0-9]{3})$",
    "IN_CIN_CD": "^[A-Z0-9]{21}$",
    "IN_PAN_CD": "^[A-Z0-9]{10}$",
    "IT_CCIAA_CD": "^[A-Z]{2}[0-9]{7}$",
    "IT_CF_CD": "^[0-9]{11}$",
    "IT_UCITS_CD": "^[0-9]{1,7}$",
    "JP_CN_CD": "^[1-9][0-9]{12}$",
    "LT_INV_CD": "(^[A-Z]{1}[0-9]{3}$)|(^SF[0-9]{3}$)|(^[A-Z]{3}-[0-9]{2}/[0-9]{2}$)|(^[A-Z]{3}-[A-Z]{4}$)",
    "LT_JAR_CD": "^[0-9]{9}$",
    "LU_RCS_CD": "^[A-Z][0-9]+$",
    "LU_VAT_CD": "^[0-9]{8}$",
    "LU_IF_CD": "^[A-Z][0-9]{6}C[0-9]{5}$",
    "LV_FON_CD": "(^LVAF[0-9]{3}[AB0-9]{1}[0-9]{2}$)|(^LVIF[0-9]{3}[ABCDEF0-9]{1}[0-9]{2}$)|(^LVB[0-9]{6}$)"
                 "|(^LVVF[0-9]{6}$)|(^LV[0-9]{11}$)",
    "LV_NBR_CD": "^[0-9]{11}$",
    "LV_VAT_CD": "^LV[0-9]{11}$",
    "MC_CIB": "^[0-9]{5}$",
    "MC_NIS_CD": "^[0-9]{2,4}[A-Z][0-9]{5}$",
    "MC_RCI_CD": "^[0-9]{2}[A-Z]{1,3}[0-9]{5}$",
    "MH_NBR_CD": "^[0-9]{4,6}$",
    "MT_VAT_CD": "^[0-9]{8}$",
    "MX_RFC_CD": "^[A-Z]{3}-[0-9]{6}-[A-Z0-9]{3}$",
    "NL_KVK_CD": "^[0-9]{8}$",
    "NL_RSIN_CD": "^[0-9]{9}$",
    "NO_NBR_CD": "^[0-9]{9}$",
    "PL_KRS_CD": "^[0-9]+$",
    "PL_NIP_CD": "^[0-9]{10}$",
    "PL_REGON_CD": "(^[0-9]{9}$)|(^[0-9]{14}$)",
    "PL_VAT_CD": "^PL[0-9]{10}$",
    "PT_FSA_CD": "^[0-9]{1,6}$",
    "PT_NIF_CD": "^[0-9]{9}$",
    "RO_CUI_CD": "^RO[0-9]{1,10}$",
    "RO_TAX_CD": "^RO[0-9]{1,10}$",
    "RO_TRN_CD": "^J[0-9]{2}/[0-9]{1,9}/[12][0-9]{3}$",
    "RU_INN_CD": "^[0-9]{10}$",
    "RU_OGRN_CD": "^[0-9]{13}$",
    "SE_FIN_CD": "^[0-9]{5}$",
    "SE_ORG_CD": "^[0-9]{2}[2-9][0-9]{3}-?[0-9]{4}$",
    "SE_MOM_CD": "^SE[0-9]{12}$",
    "SI_DAV_CD": "^[0-9]{8}$",
    "SI_DDV_CD": "^SI[0-9]{8}$",
    "SI_MAT_CD": "^[0-9]{10}$",
    "SK_ICO_CD": "^[0-9]{8}$",
    "SK_IF_CD": "^SK[0-9]{8}[A-Z]{3}[0-9]{2}$",
    "TR_VKN_CD": "^[0-9]{1,10}$",
    "US_EIN_CD": "^[0-9]{2}-[0-9]{7}$",
    "US_DSFN_CD": "^[0-9]{7}$",
    "US_CIK_CD": "^[0-9]{10}$",
}

# List of other identifiers issued by Narodná banka Slovenska
NBS_IDENTIFIERS = {
    "ICO_NI": "^[0-9]{8}[a-z]{1}$",  # IČO NI is issued by NBS for subjects with duplicate national identifier (IČO).
    "NIC": "^[0-9]{8}N[0-9]{6}$",  # NIČ is issued by NBS for foreign (non SK) subjects.
}

# List of both NBS and ECB identifiers
IDENTIFIER_FORMATS = {**ECB_NATIONAL_IDENTIFIERS, **NBS_IDENTIFIERS}

# List of exceptions when checking identifier country, used in formats.verify_national_identifier_country
GEN_IDENTIFIER_COUNTRY_EXCEPTIONS = ("BR", "CA", "CH", "CN", "GB", "HK", "IN", "JP", "MH", "MX", "NO", "RU", "TR", "US")
